###
POST http://localhost:8080/profile/add-profile
Content-Type: application/json

{
  "name": "MahmudjonModer",
  "surname": "Foziljonov",
  "email": "abb@gmail.com",
  "phone": "+998935951747",
  "password": "123",
  "role": "MODERATOR"
}

### Update Profile
PUT http://localhost:8080/profile/update/1
Content-Type: application/json

{
  "id": 0,
  "name": "Max",
  "surname": "",
  "email": "",
  "phone": "",
  "password": "",
  "status": "PUBLISHED",
  "role": "ADMIN"
}

### Get All Profiles
GET http://localhost:8080/profile/get-all?
    page=1&
    size=10

### Filter Profile
POST http://localhost:8080/profile/filter
Content-Type: application/json

{
  "id": 0,
  "name": "",
  "surname": "",
  "email": "",
  "phone": "",
  "password": "",
  "status": "PUBLISHED",
  "role": "ADMIN",
  "createdDate": ""
}

### Registration
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "bigmangcom@gmail.com",
  "password": "123456"
}


### Update
PUT http://localhost:8080/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiYWJ2QGdtYWlsLmNvbSIsInN1YiI6ImFidkBnbWFpbC5jb20iLCJpYXQiOjE3MzAzODQ3MjAsImV4cCI6MTczMDQ3MTEyMH0.K9oeXHyO81srloW0xxFvYCD-S4KkW9Ou-_5EMYN_Lt4

{
  "name": "Makhmudjon",
  "surname": "Foziljonov"
}

###
POST http://localhost:8080/profile/add-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiYWJ2QGdtYWlsLmNvbSIsInN1YiI6ImFidkBnbWFpbC5jb20iLCJpYXQiOjE3MzAzMDU3NzIsImV4cCI6MTczMDM5MjE3Mn0.CSoyro3XxfyJ7YGz2i7BfvIom-gKu9E3pmtJLpFs8tI

{
  "name": "Mahmud",
  "surname": "Foziljonov",
  "email": "foziljonov2@gmail.com",
  "phone": "+998931234567",
  "password": "123",
  "role": "ROLE_USER"
}