POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "id": 0,
  "name": "Makhmudjon",
  "surname": "Foziljonov",
  "email": "test@gmail.com",
  "phone": "999",
  "password": "12345",
  "status": "PUBLISHED",
  "role": "ADMIN"
}

### Update Profile
PUT http://localhost:8080/profile/update/1
Content-Type: application/json

{
  "id": 0,
  "name": "Max",
  "surname": "",
  "email": "",
  "phone": "",
  "password": "",
  "status": "PUBLISHED",
  "role": "ADMIN"
}

### Get All Profiles
GET http://localhost:8080/profile/get-all?
    page=1&
    size=10

### Filter Profile
POST http://localhost:8080/profile/filter
Content-Type: application/json

{
  "id": 0,
  "name": "",
  "surname": "",
  "email": "",
  "phone": "",
  "password": "",
  "status": "PUBLISHED",
  "role": "ADMIN",
  "createdDate": ""
}

### Registration
POST localhost:8081/auth/login
Content-Type: application/json

{
  "email": "bigmangcom@gmail.com",
  "password": "12345"
}
