###
POST http://localhost:8080/save?
    id=fea43b7d-e6e2-42d1-a5a3-a7e2950d0b2f
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiYWJhQGdtYWlsLmNvbSIsInN1YiI6ImFiYUBnbWFpbC5jb20iLCJpYXQiOjE3MzE3NTMyMDAsImV4cCI6MTczMTgzOTYwMH0.xC87JBa9VMNatK1vlfl46Y43pTfBew6VQ8fqPQO7p9M

### delete
DELETE http://localhost:8080/save/delete?
    id=fea43b7d-e6e2-42d1-a5a3-a7e2950d0b2f
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiYWJhQGdtYWlsLmNvbSIsInN1YiI6ImFiYUBnbWFpbC5jb20iLCJpYXQiOjE3MzE3NTMyMDAsImV4cCI6MTczMTgzOTYwMH0.xC87JBa9VMNatK1vlfl46Y43pTfBew6VQ8fqPQO7p9M


###
GET http://localhost:8080/save/get-all
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiYWJhQGdtYWlsLmNvbSIsInN1YiI6ImFiYUBnbWFpbC5jb20iLCJpYXQiOjE3MzE3NTMyMDAsImV4cCI6MTczMTgzOTYwMH0.xC87JBa9VMNatK1vlfl46Y43pTfBew6VQ8fqPQO7p9M
